// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: chat.sql

package db

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO "Chat" (username) VALUES ($1) RETURNING chat_id, username
`

func (q *Queries) CreateChat(ctx context.Context, username string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, username)
	var i Chat
	err := row.Scan(&i.ChatID, &i.Username)
	return i, err
}

const getUserChat = `-- name: GetUserChat :many
SELECT "chat_id" FROM "Chat" WHERE username = $1
`

func (q *Queries) GetUserChat(ctx context.Context, username string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getUserChat, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var chat_id int32
		if err := rows.Scan(&chat_id); err != nil {
			return nil, err
		}
		items = append(items, chat_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
