// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "User" (username) VALUES ($1) RETURNING username
`

func (q *Queries) CreateUser(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, createUser, username)
	err := row.Scan(&username)
	return username, err
}

const getUser = `-- name: GetUser :one
SELECT username FROM "User" WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	err := row.Scan(&username)
	return username, err
}
