DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "QA" CASCADE;
DROP TABLE IF EXISTS "Chat" CASCADE;
DROP TABLE IF EXISTS "Message" CASCADE;

DROP FUNCTION IF EXISTS "message_no_increment" CASCADE;